a = float(input())
b = float(input())
c = float(input())
d = float(input())
e = float(input())
f = float(input())
x = (d * e - b * f) / (d * a - c * b)
y = (f * a - e * c) / (d * a - b * c)
print(x, y)
